### ISSUE TITLE
display issue / MR titles

### ISSUE THREAD

**Issue by ollieparanoid** [z3ntu/pmos-bot#1]
Ha, you didn't disable the issues ;D How about displaying the titles, so people roughly know what they will get before clicking the links?

**Comment by z3ntu** [comment]
Matrix does a link preview by itself (if enabled). And actually fetching the page to get the title, etc. would complicate things a lot ;)

But after checking, all postmarketOS rooms have link previews disabled by default (`URL previews are disabled by default for participants in this room.`) so maybe we should enable them?

**Comment by ollieparanoid** [comment]
Good point... I wonder why we disabled that.
Let's discuss this here:
https://gitlab.com/postmarketOS/postmarketos.org/issues/91
