### ISSUE TITLE
move to postmarketOS gitlab org

### ISSUE THREAD

**Issue by ollieparanoid** [z3ntu/pmos-bot#3]
How about we do that?

**Comment by z3ntu** [comment]
![image](https://user-images.githubusercontent.com/3768500/50294064-55485800-0475-11e9-975f-20d8cb990b12.png)

Hmmm...

**Comment by ollieparanoid** [comment]
Done: https://gitlab.com/postmarketOS/matrix-bot

Now you can join the tradition of changing the project description to the following, and then archiving the repository :smile: 

> `Repository has been moved! https://postmarketos.org/move.html#/matrix-bot :truck: :truck: :truck:`

**Comment by z3ntu** [comment]
Done.
